### ISSUE TITLE
Supercharge Propoplex with ChatGPT Integration!

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Propoplex#1]
We're on the brink of completing Propoplex's front-end and are excited to add ChatGPT API integration to the platform. With ChatGPT's advanced language processing capabilities, our users will be able to create even more engaging proposals that are tailored to their clients' needs. We're looking for a developer to help us integrate ChatGPT API seamlessly into Propoplex's workflow, making the proposal writing process even smoother and more efficient. Join us in taking Propoplex to the next level! If you find an issue that you would like to work on, you can simply comment on the issue to let us know that you are working on it. This will help us avoid having multiple contributors working on the same issue at the same time.

**Comment by Hilary017** [comment]
Is anyone currently handling this? Or I should go ahead and give it a try?

**Comment by MohamedMafaz** [comment]
Congratulations! You have been assigned this exciting task, and to make your journey smoother, I'll provide you with the ChatGPT 3 API Key. Just drop your email id, and let's get started! And if you're using PostmanAPI, that's even better

**Comment by MohamedMafaz** [comment]
Let's make sure your hard work gets the spotlight it deserves! Don't forget to submit your PR with a live link hosted on Github Pages. Just drop a comment on your estimated PR submission time, and we'll handle the rest. I'll provide the prompt you need to send to ChatGPT, in it you need to put input given by user on forms

**Comment by MohamedMafaz** [comment]
Hey @Hilary017 
Reply me when you start working on it

**Comment by MohamedMafaz** [comment]
Hey @Hilary017 
Are you there?

**Comment by MohamedMafaz** [comment]
We made it with the help of BardAPI. So I closed this issue
