### ISSUE TITLE
the hover effect is applied to the first link before hovering over it.

### ISSUE THREAD

**Issue by naim16031988** [MohamedMafaz/Propoplex#16]
before hovering over the navbar, all the navbar links should have the regular style which is white background. in our case, the home link has the hovering style. Which is light grey. we want to remove that and apply the white style to the Home
link in the navbar. and make it light grey when a user hover over it .

**Comment by MohamedMafaz** [comment]
If we did it, then how user can understand which page they are viewing?

**Comment by naim16031988** [comment]
all right. So, the grey style should be on the selected link. for example, if a user hit the About us link, it should turn grey. and all the other links should be white. 
let me propose a solution and we can discuss it .

**Comment by MohamedMafaz** [comment]
Thank you so much @naim16031988 for making an PR on this issue.
