### ISSUE TITLE
no hover behavior on Go Premium button

### ISSUE THREAD

**Issue by naim16031988** [MohamedMafaz/Propoplex#17]
One issue observed on the website is related to the behavior when hovering over the Go Premium button. When a user hovers over it , there is no visual indication or feedback to signify that the link is interactive or clickable. This lack of hover effect can result in a poor user experience and confusion for visitors.

**Comment by MohamedMafaz** [comment]
Ok! Can you work on this? Otherwise I'll do it. No problem

**Comment by naim16031988** [comment]
Yeah go for it

**Comment by MohamedMafaz** [comment]
I added an hover effect for it. So, I close this issue

**Comment by naim16031988** [comment]
Ok good job
