### ISSUE TITLE
form submit button is not centered on the mobile version 

### ISSUE THREAD

**Issue by naim16031988** [MohamedMafaz/Propoplex#18]
One issue observed on the website is related to the  lack of centering of a Submit Button. When viewing the website, it is noticeable that a submit button is not properly centered within their designated area.
The misalignment of the button(s) can lead to visual inconsistencies and disrupt the overall aesthetics of the webpage. It may create an unbalanced or cluttered appearance, making it difficult for users to locate and interact with the button(s) easily.

**Comment by MohamedMafaz** [comment]
Got it bro. I'll work on this

**Comment by MohamedMafaz** [comment]
Fixed. So I close this issue

**Comment by naim16031988** [comment]
Ok good
