### ISSUE TITLE
Enhancing User Experience by Restricting Card Selection in Our Products Section

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Propoplex#2]
Our products section has a wide range of cards that users can choose from. However, we've noticed that users are able to select multiple cards simultaneously, which can create confusion and frustration. To enhance the user experience and streamline the selection process, we need to implement a restriction that allows users to select only one card at a time.

As an open issue, we're inviting contributors to help us find the best solution for this problem. The selected solution should not only meet our technical requirements but also improve the overall usability of our products section. Join us in creating a better user experience for our customers by tackling this issue today!

**Comment by barry-g1076** [comment]
Hey I checked out the website and found the issue. my solution to this would be that we use the buttons on the cards to select and deselect the cards. so if a user selected proposal writer for example and then went to select bio writer it would deselect proposal writer and set bio writer as the selected option.

**Comment by MohamedMafaz** [comment]
Sounds Good! I assigned this issue for you. When submitting your PR Make sure to give a live link which is hosted in Github Pages

**Comment by barry-g1076** [comment]
Ok Done

**Comment by MohamedMafaz** [comment]
Dear valued contributor,

Thank you for your outstanding contribution! Your hard work and dedication have not gone unnoticed, and your commitment to excellence is truly inspiring. Your contributions will be forever engraved in the history of our project.

As a token of appreciation, I would like to extend my blessings to you. May you continue to soar to new heights and touch the very peak of programming. Your talents and expertise are invaluable, and I have no doubt that you will achieve great success in all your future endeavors.

Thank you once again for your exceptional work.
