### ISSUE TITLE
make the contact,About and login pages responsive :

### ISSUE THREAD

**Issue by naim16031988** [MohamedMafaz/Propoplex#21]
As we have done with the home page, we should make contact, about and login pages responsive and 
mobile screen friendly. 
make the navbar collapsing in a small screen and, place properly all the contents of those 3 pages

**Comment by MohamedMafaz** [comment]
Yeah! I'll assign this issue to you. Good luck! But try to create a file called navbar.html. navbar.css.  So that wherever we want we can easily call it.

**Comment by naim16031988** [comment]
Yes i will do that

**Comment by MohamedMafaz** [comment]
Hey @naim16031988 
I checked out the link you given. I saw that About, Login, Request New Tool pages aren't look responsive. Even the navbar also not collapsed. Can you please check it out?
