### ISSUE TITLE
missing icons in the navbar of login page 

### ISSUE THREAD

**Issue by naim16031988** [MohamedMafaz/Propoplex#22]
there is no any icon visible on the login page 
<img width="671" alt="Screenshot 2023-05-26 132932" src="https://github.com/MohamedMafaz/Propoplex/assets/125624860/b63cac63-efa1-49cb-9006-2ff76e2ba289">

**Comment by Shubh8899** [comment]
I would like to work on this one.

**Comment by MohamedMafaz** [comment]
I assigned both of you. Good luck
