### ISSUE TITLE
Need to Change the Text Style in Navbar in Login Page

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Propoplex#25]
This open contribution opportunity addresses an issue with the login page's navbar where all the texts appear bolder compared to other pages. We are seeking community input and contributions to rectify this inconsistency and ensure consistent text styling throughout our website. Join us in improving the user experience by making the navbar's text styling align with the rest of the pages. Help us create a cohesive visual experience for our users by participating in this exciting enhancement project.

**Comment by KrownWealth** [comment]
I would love to fix this issue by rectifying the text style in the Navbar on the Login page

**Comment by MohamedMafaz** [comment]
Ok! I'll assign this issue to you. Good Luck!

**Comment by MohamedMafaz** [comment]
Need live link

**Comment by KrownWealth** [comment]
If this is permitted without a restrcition, attached below is the github pages live link to the branch I made the changes on, So that you can see.

https://krownwealth.github.io/Propoplex/login.html

**Comment by MohamedMafaz** [comment]
Hey @KrownWealth 
I close this issue. Thanks for your contribution.
