### ISSUE TITLE
Upgrade your Website to React.js

### ISSUE THREAD

**Issue by arpittyagi102** [MohamedMafaz/Propoplex#35]
hey @MohamedMafaz,
I wanted to make you an offer to elevate your website with popular javascript framework REACT JS . React is today's standard for making modern website. It brings cutting-edge capabilities, including enhanced performance, modular development, interactive features, and a thriving community of developers. As an  React developer, I would love to convert your website to React js and unlock its full potential.
But as i will be completing your whole website by myself as a freelancer it cannot be a free of cost contribution. 
Reply back to explore possibilities.

**Comment by MohamedMafaz** [comment]
Hey @MohamedMafaz 
We don't need any freelancing service now. Also, I don't know React.js If I convert my website to react it's too hard to edit in future.
