### ISSUE TITLE
Interactive Card Selector: Engage Users with Dynamic Color Changes

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Propoplex#4]
With this issue, we are inviting contributors to add an exciting feature to our web application. When a user selects a card, the color of the card should change, giving the application a vibrant and interactive feel. You don't need permission to start working on this issue; just jump right in and get started! We only ask that you provide us with a live link hosted on Github Pages so we can see your changes in action. Let's make our cards come alive and give our users an unforgettable experience!

**Comment by Daydreamofpeach** [comment]
//add to css file, replace current card definition if that exists.   you will also need to have a card2 className on a second card to generate full shading effect.



.card {
 width: 190px;
 height: 254px;
 background-image: linear-gradient(163deg, #00ff75 0%, #3700ff 100%);
 border-radius: 20px;
 transition: all .3s;
}

.card2 {
 width: 190px;
 height: 254px;
 background-color: #1a1a1a;
 border-radius:;
 transition: all .2s;
}

.card2:hover {
 transform: scale(0.98);
 border-radius: 20px;
}

.card:hover {
 box-shadow: 0px 0px 30px 1px rgba(0, 255, 117, 0.30);
}

**Comment by MohamedMafaz** [comment]
Can you submit a PR?

**Comment by MohamedMafaz** [comment]
Is anyone is willing to submit PR with this code?. You can submit a PR

**Comment by MohamedMafaz** [comment]
Hey @Daydreamofpeach 
I unassigned you because of inactive. Anyone can submit PR with this code. Thanks @Daydreamofpeach for your valuable contribution

**Comment by MohamedMafaz** [comment]
Our contributor Naim working on this issue. So, other contributors may look into other issues
