### ISSUE TITLE
Adding a Striking Navbar and Revamping Glass Color on Contact Us Page

### ISSUE THREAD

**Issue by MohamedMafaz** [MohamedMafaz/Propoplex#7]
Our Contact Us page is a crucial element of our website, acting as a primary gateway for users to get in touch with us. To further enhance user experience and aesthetics, we have identified two key areas of improvement. 

**1. Adding a Captivating Navbar:** Currently, our Contact Us page lacks a prominent navigation bar, which can make it challenging for users to navigate seamlessly within our site. By incorporating an eye-catching and user-friendly navbar, we aim to provide visitors with clear and intuitive options to explore different sections of our website. The navbar will serve as a visual guide, facilitating easy access to vital information and ensuring a delightful user experience.

**2. Transforming Glass Color:** The current color scheme of the glass elements on our Contact Us page does not align with our brand identity or modern design trends. We plan to revamp the glass color to create a visually appealing and harmonious experience for our users. The new color will be carefully chosen to complement our website's overall aesthetics, evoking a sense of trust, professionalism, and modernity.

By addressing these two aspects, we aim to elevate the visual appeal and usability of our Contact Us page, ensuring that users can effortlessly navigate our site and engage with our business. This enhancement will contribute to a positive impression of our brand and encourage visitors to reach out to us more confidently.

**Comment by MwendwaDev** [comment]
I would love to work on this

**Comment by MohamedMafaz** [comment]
You were assigned to this issue. Good luck 👍

**Comment by MwendwaDev** [comment]
Do you want the navbar to be the same as the one in the home page?

**Comment by MohamedMafaz** [comment]
Yeah!

**Comment by MwendwaDev** [comment]
Maybe you could let me know the exact colors needed for the contact section please?. I see the website has a couple of different colors.

**Comment by MohamedMafaz** [comment]
Hey @MwendwaDev 
Take a look at [this UI](https://www.figma.com/file/TXhhXaEEJ5OxDBWVDIEpvk/Propoplex?type=design&node-id=0%3A1&t=zofnyDHOXIdPmHyI-1)
